import {
  fixedToDisplayNumber,
  generateBattlePathWithActiveEngine,
  generateRoundPathWithActiveEngine,
} from '../engine'
import type { StrikefallPathPoint } from '../wasm'
import type {
  BattleIntervalExtrema,
  Candle,
  DeckDefinition,
  FixedBattleIntervalExtrema,
} from './types'
import { roundTo } from './math'

export const LINE_ORIGIN = 50
export const DEFAULT_APPROACH_CANDLES = 18
export const DEFAULT_BATTLE_STEPS = 241
/** Canonical Rust deck variance: 8% total log standard deviation. */
export const BATTLE_INTEGRATED_VARIANCE = 0.0064
export const APPROACH_INTEGRATED_VARIANCE = BATTLE_INTEGRATED_VARIANCE / 4
export const NEUTRAL_DRIFT_PER_VARIANCE = -0.5

export interface GeneratedPaths {
  approach: Candle[]
  battlePath: number[]
  battlePathFixed: string[]
  battleExtrema: BattleIntervalExtrema[]
  battleExtremaFixed: FixedBattleIntervalExtrema[]
  lineValue: number
  lineValueFixed: string
}

export interface PathExtrema {
  minimum: number
  maximum: number
  range: number
}

function engineDeckInput(deck: DeckDefinition) {
  return {
    id: deck.id,
    name: deck.name,
    version: deck.version,
    monitoringConvention: deck.monitoringConvention,
    variance: deck.variance,
    openingRunway: deck.openingRunway,
  }
}

/**
 * Floating reference schedule used only by analytics/tests. Production path
 * generation and Escape variance both execute through the Rust/WASM core.
 */
export function varianceSchedule(
  deck: DeckDefinition,
  increments: number,
  integratedVariance: number,
): number[] {
  if (!Number.isInteger(increments) || increments < 1) {
    throw new RangeError('Path increments must be a positive integer')
  }
  if (!Number.isFinite(integratedVariance) || integratedVariance <= 0) {
    throw new RangeError('Integrated variance must be positive')
  }
  if (deck.variance.some((weight) => !Number.isFinite(weight) || weight <= 0)) {
    throw new RangeError('Every deck variance weight must be positive')
  }
  const rawWeights = Array.from({ length: increments }, (_, index) => {
    const progress = (index + 0.5) / increments
    return deck.variance[Math.min(3, Math.floor(progress * 4))] as number
  })
  const totalWeight = rawWeights.reduce((sum, weight) => sum + weight, 0)
  const schedule = rawWeights.map((weight) => (weight / totalWeight) * integratedVariance)
  const runway = deck.openingRunway
  const firstQuarterSteps = Math.floor(increments / 4)
  if (!runway || increments % 4 !== 0 || runway.steps >= firstQuarterSteps) return schedule

  const firstQuarterVariance = schedule
    .slice(0, firstQuarterSteps)
    .reduce((sum, value) => sum + value, 0)
  const runwayVariance = firstQuarterVariance * runway.varianceShareBps / 10_000
  const catchupSteps = firstQuarterSteps - runway.steps
  for (let index = 0; index < firstQuarterSteps; index += 1) {
    schedule[index] = index < runway.steps
      ? runwayVariance / runway.steps
      : (firstQuarterVariance - runwayVariance) / catchupSteps
  }
  return schedule
}

/**
 * Reference inversion for the one-sided conditional bridge-extremum law.
 * The actual gameplay extrema are generated by `strikefall-core`.
 */
export function sampleBridgeExtrema(
  open: number,
  close: number,
  variance: number,
  upperUniform: number,
  lowerUniform: number,
): BattleIntervalExtrema {
  if (!(open > 0) || !(close > 0) || !(variance > 0)) {
    throw new RangeError('Bridge extrema require positive endpoints and variance')
  }
  if (!(upperUniform > 0 && upperUniform < 1) || !(lowerUniform > 0 && lowerUniform < 1)) {
    throw new RangeError('Bridge extrema uniforms must be inside (0, 1)')
  }
  const openingLog = Math.log(open)
  const closingLog = Math.log(close)
  const deltaSquared = (openingLog - closingLog) ** 2
  const root = (uniform: number) =>
    Math.sqrt(deltaSquared - 2 * variance * Math.log(uniform))
  const upperLog = (openingLog + closingLog + root(upperUniform)) / 2
  const lowerLog = (openingLog + closingLog - root(lowerUniform)) / 2
  return {
    high: roundTo(Math.max(open, close, Math.exp(upperLog))),
    low: roundTo(Math.min(open, close, Math.exp(lowerLog))),
  }
}

function fixed(point: StrikefallPathPoint, field: 'price' | 'intervalHigh' | 'intervalLow'): number {
  return fixedToDisplayNumber(point[field], `${field}[${point.step}]`)
}

function boundaryIndexes(intervals: number, buckets: number): number[] {
  if (!Number.isInteger(buckets) || buckets < 1 || buckets > intervals) {
    throw new RangeError(`Display buckets must be between 1 and ${intervals}`)
  }
  return Array.from(
    { length: buckets + 1 },
    (_, index) => Math.floor((index * intervals) / buckets),
  )
}

/** Aggregates Rust microsteps without discarding any bridge interval extrema. */
export function candleizeCanonicalPath(
  points: readonly StrikefallPathPoint[],
  candleCount: number,
): Candle[] {
  const intervals = points.length - 1
  const boundaries = boundaryIndexes(intervals, candleCount)
  return Array.from({ length: candleCount }, (_, index) => {
    const start = boundaries[index] as number
    const end = boundaries[index + 1] as number
    const open = fixed(points[start] as StrikefallPathPoint, 'price')
    const close = fixed(points[end] as StrikefallPathPoint, 'price')
    let high = open
    let low = open
    for (let pointIndex = start + 1; pointIndex <= end; pointIndex += 1) {
      const point = points[pointIndex] as StrikefallPathPoint
      high = Math.max(high, fixed(point, 'intervalHigh'))
      low = Math.min(low, fixed(point, 'intervalLow'))
    }
    return { open, high, low, close }
  })
}

function displayBattle(
  points: readonly StrikefallPathPoint[],
  displayPoints: number,
): Pick<
  GeneratedPaths,
  'battlePath' | 'battlePathFixed' | 'battleExtrema' | 'battleExtremaFixed'
> {
  const intervals = points.length - 1
  if (!Number.isInteger(displayPoints) || displayPoints < 2 || displayPoints > points.length) {
    throw new RangeError(`Battle display points must be between 2 and ${points.length}`)
  }
  const boundaries = boundaryIndexes(intervals, displayPoints - 1)
  const firstPoint = points[0] as StrikefallPathPoint
  const first = fixed(firstPoint, 'price')
  const battlePathFixed = boundaries.map((boundary) =>
    (points[boundary] as StrikefallPathPoint).price,
  )
  const battlePath = battlePathFixed.map((value, index) =>
    fixedToDisplayNumber(value, `price[${boundaries[index]}]`),
  )
  const battleExtrema: BattleIntervalExtrema[] = [{ high: first, low: first }]
  const battleExtremaFixed: FixedBattleIntervalExtrema[] = [{
    high: firstPoint.price,
    low: firstPoint.price,
  }]
  for (let index = 1; index < boundaries.length; index += 1) {
    const start = boundaries[index - 1] as number
    const end = boundaries[index] as number
    let high = battlePath[index - 1] as number
    let low = high
    let highFixed = battlePathFixed[index - 1] as string
    let lowFixed = highFixed
    for (let pointIndex = start + 1; pointIndex <= end; pointIndex += 1) {
      const point = points[pointIndex] as StrikefallPathPoint
      high = Math.max(high, fixed(point, 'intervalHigh'))
      low = Math.min(low, fixed(point, 'intervalLow'))
      if (BigInt(point.intervalHigh) > BigInt(highFixed)) highFixed = point.intervalHigh
      if (BigInt(point.intervalLow) < BigInt(lowFixed)) lowFixed = point.intervalLow
    }
    battleExtrema.push({ high, low })
    battleExtremaFixed.push({ high: highFixed, low: lowFixed })
  }
  return { battlePath, battlePathFixed, battleExtrema, battleExtremaFixed }
}

export function generateApproach(
  seed: string,
  deck: DeckDefinition,
  candleCount = DEFAULT_APPROACH_CANDLES,
  start = LINE_ORIGIN,
): Candle[] {
  const raw = generateRoundPathWithActiveEngine(engineDeckInput(deck), seed, start)
  return candleizeCanonicalPath(raw.approach, candleCount)
}

export function generateCanonicalBattlePaths(
  seed: string,
  deck: DeckDefinition,
  start: number,
  displayPoints = DEFAULT_BATTLE_STEPS,
): Pick<
  GeneratedPaths,
  'battlePath' | 'battlePathFixed' | 'battleExtrema' | 'battleExtremaFixed'
> {
  if (!Number.isFinite(start) || start <= 0) {
    throw new RangeError('Path start must be positive')
  }
  const raw = generateBattlePathWithActiveEngine(engineDeckInput(deck), seed, start)
  return displayBattle(raw, displayPoints)
}

export function generateBattlePath(
  seed: string,
  deck: DeckDefinition,
  start: number,
  steps = DEFAULT_BATTLE_STEPS,
): number[] {
  return generateCanonicalBattlePaths(seed, deck, start, steps).battlePath
}

export function generateBattleExtrema(
  seed: string,
  deck: DeckDefinition,
  battlePath: readonly number[],
): BattleIntervalExtrema[] {
  const start = battlePath[0]
  if (start === undefined) throw new RangeError('Battle path cannot be empty')
  const generated = generateCanonicalBattlePaths(seed, deck, start, battlePath.length)
  if (
    generated.battlePath.length !== battlePath.length
    || generated.battlePath.some((value, index) => value !== battlePath[index])
  ) {
    throw new Error('Battle path does not match the canonical Rust seed stream')
  }
  return generated.battleExtrema
}

export function generateRoundPaths(
  seed: string,
  deck: DeckDefinition,
  approachCandles = DEFAULT_APPROACH_CANDLES,
  battleSteps = DEFAULT_BATTLE_STEPS,
): GeneratedPaths {
  const raw = generateRoundPathWithActiveEngine(engineDeckInput(deck), seed, LINE_ORIGIN)
  const approach = candleizeCanonicalPath(raw.approach, approachCandles)
  const battle = displayBattle(raw.battle, battleSteps)
  const lineValue = battle.battlePath[0] as number
  const lineValueFixed = battle.battlePathFixed[0] as string
  return { approach, ...battle, lineValue, lineValueFixed }
}

export function getPathExtrema(path: readonly number[]): PathExtrema {
  if (path.length === 0) {
    throw new RangeError('Cannot inspect an empty path')
  }
  const minimum = Math.min(...path)
  const maximum = Math.max(...path)
  return { minimum, maximum, range: maximum - minimum }
}

export function battleStandardDeviation(start: number): number {
  return start * Math.sqrt(Math.exp(BATTLE_INTEGRATED_VARIANCE) - 1)
}
